apiVersion: v1
kind: Service
metadata:
  name: my-project-service
  labels:
    app: my-project
spec:
  type: LoadBalancer
  selector:
    app: my-project # Matches pods with the "app: my-app" label
  ports:
    - protocol: TCP
      port: 80        # External port for the load balancer
      targetPort: 3000  # Port on the container