name: Pipeline with Smoke Tests (trivy removed)

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t $IMAGE_NAME:$COMMIT_SHA .
        docker tag $IMAGE_NAME:$COMMIT_SHA $IMAGE_NAME:latest

    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker push $IMAGE_NAME:$COMMIT_SHA
        docker push $IMAGE_NAME:latest

    # - name: Install Trivy
    #   run: |
    #     curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    #     echo "Adding Trivy to PATH..."
    #     export PATH=$PATH:$HOME/bin:$HOME/.local/bin
    #     echo "PATH=$PATH" >> $GITHUB_ENV
    #     ls -l $HOME/bin
    #     ls -l $HOME/.local/bin
    #     trivy --version

    # - name: Update Trivy Database
    #   run: trivy image --download-db-only

    # - name: Scan Docker image with Trivy
    #   run: |
    #     IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
    #     COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
    #     docker pull $IMAGE_NAME:$COMMIT_SHA
    #     trivy image --debug --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$COMMIT_SHA

  smoke-tests:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Smoke Tests
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker run --rm $IMAGE_NAME:$COMMIT_SHA ./smoke.sh