name: Pipeline with Trivy and Smoke Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and tag the Docker image
    - name: Build and tag Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t $IMAGE_NAME:$COMMIT_SHA .
        docker tag $IMAGE_NAME:$COMMIT_SHA $IMAGE_NAME:latest

    # Step 5: Push the Docker image to the registry
    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker push $IMAGE_NAME:$COMMIT_SHA
        docker push $IMAGE_NAME:latest

    # Step 6: Install Trivy
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        export PATH=$PATH:$HOME/.local/bin
        trivy --version

    # Step 7: Scan the Docker image with Trivy
    - name: Scan Docker image with Trivy
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker pull $IMAGE_NAME:$COMMIT_SHA
        trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$COMMIT_SHA

  smoke-tests:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Run smoke tests
    - name: Run Smoke Tests
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cuci-repo"
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker run --rm $IMAGE_NAME:$COMMIT_SHA ./smoke.sh